-----------------------------------------------------------------------------
--                          LAB TASKS PROBLEM
-----------------------------------------------------------------------------

--Q1)
   SELECT * FROM JOBS;

--Q2)
   SELECT MIN_SALARY, MAX_SALARY FROM JOBS WHERE JOB_TITLE = 'President';

--Q3)
   SELECT *FROM EMPLOYEES WHERE SALARY > 20000;

--Q4)
   SELECT JOB_ID FROM EMPLOYEES WHERE SALARY >= 15000;

--Q5)
   SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME = 'Snares';

--Q6)
   SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 57;

--Q7)
   SELECT PHONE_NUMBER FROM EMPLOYEES WHERE DEPARTMENT_ID = 80 AND MANAGER_ID = 100;

--Q8)
   SELECT * FROM EMPLOYEES WHERE FIRST_NAME IN ('John', 'NEENA', 'Lency');   -- if i follow the case given in question
   SELECT * FROM EMPLOYEES WHERE FIRST_NAME IN ('John', 'Neena', 'Lency');   -- if i follow the hr table case style

--Q9)
   SELECT CITY FROM LOCATIONS WHERE COUNTRY_ID = 'IT';

--Q10)
   SELECT CITY FROM LOCATIONS WHERE COUNTRY_ID NOT IN ('IN', 'CH');

--Q11)
   SELECT * FROM JOBS WHERE MIN_SALARY > 8000 AND MIN_SALARY < 15000;

--Q12)
   SELECT PHONE_NUMBER FROM EMPLOYEES WHERE DEPARTMENT_ID = 90 AND JOB_ID <> 'IT_PROG';

--Q13)
   SELECT * FROM EMPLOYEES WHERE HIRE_DATE > '12-Dec-07';

--Q14)
   SELECT * FROM EMPLOYEES WHERE HIRE_DATE > '12-Dec-07' AND DEPARTMENT_ID = 100; 

--Q15)
   SELECT * FROM EMPLOYEES WHERE HIRE_DATE > '12-Dec-07' AND DEPARTMENT_ID <> 100; 

--Q16)
   SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT = 0 AND DEPARTMENT_ID NOT IN (90,100);

--Q17
   SELECT * FROM EMPLOYEES WHERE HIRE_DATE > '31-DEC-09' AND HIRE_DATE < '1-JAN-11';

--Q18)
   SELECT * FROM JOBS WHERE MIN_SALARY > 8000 AND MIN_SALARY < 15000;

--Q19)
   SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID FROM EMPLOYEES WHERE (EMPLOYEE_ID > 100 AND EMPLOYEE_ID < 150 AND DEPARTMENT_ID > 90 AND DEPARTMENT_ID < 100);

--Q20)
--    WE ARE TOLD TO SKIP THIS QUESTION FOR NOW


-----------------------------------------------------------------------------
--                          LAB PRACTICE PROBLEM
-----------------------------------------------------------------------------

--Q1)
   SELECT EMAIL FROM EMPLOYEES WHERE MANAGER_ID = 101 AND DEPARTMENT_ID = 50;
    
--Q2)    
   SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_NAME IN ('Finance', 'Sales', 'SA_RE');

--Q3)
--    WE ARE TOLD TO SKIP THIS QUESTION FOR NOW

--Q4)
   SELECT * FROM EMPLOYEES WHERE SALARY < 10000;

--Q5)
   SELECT * FROM JOBS WHERE MAX_SALARY <= 20000;

--Q6)
   SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME = 'Jones'; 

--Q7)
   SELECT CITY FROM LOCATIONS WHERE COUNTRY_ID = 'IT';

--Q8)
   SELECT PHONE_NUMBER FROM EMPLOYEES WHERE DEPARTMENT_ID = 80 AND MANAGER_ID = 100; 

--Q9)
   SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales');

--Q10)
   SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'A%';

--Q11)
   SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME ='Sales') AND SALARY > 50000;