----Q1
Create audit table
    CREATE TABLE EMPLOYEE_AUDIT ( EMPLOYEE_ID NUMBER,
    FIRST NAME VARCHAR2(50),
    HIRE DATE DATE,
    INSERT_TIMESTAMP TIMESTAMP
);

---- Trigger to insert audit record on new employee
CREATE OR REPLACE TRIGGER trg_employee_insert AFTER INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEE_AUDIT (EMPLOYEE_ID, FIRST_NAME, HIRE DATE, INSERT_TIMESTAMP)
    VALUES (:NEW.EMPLOYEE_ID, NEW.FIRST_NAME, NEW.HIRE_DATE, SYSTIMESTAMP); 
    DBMS_OUTPUT.PUT_LINE('Inserted in Employee_Audit the new Employee');
END;
/

---- Insert new employee
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY)
VALUES (202, 'Test', 'User', 'testuser', '650.501.4887', SYSDATE, 'IT_PROG', 3000);

---- Check audit table
SELECT FROM EMPLOYEE_AUDIT WHERE EMPLOYEE_ID = 202;



----Q2
CREATE OR REPLACE TRIGGER trg_salary_limit BEFORE UPDATE OF SALARY ON EMPLOYEES FOR EACH ROW
BEGIN
    IF NEW.SALARY> 50000 THEN
        RAISE APPLICATION_ERROR (-20001, 'Salary cannot exceed 50,000.');
    END IF;
END;
/
-- Should FAIL
UPDATE EMPLOYEES
SET SALARY 60000
WHERE EMPLOYEE ID = 202;



----Q3
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = 60;
--- Create log table 
CREATE TABLE DEPT_LOG (
    DEPARTMENT_ID NUMBER,
    OLD_NAME VARCHAR2(50),
    NEW_NAME VARCHAR2(50),
    CHANGE_DATE TIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_dept_name_update AFTER UPDATE OF DEPARTMENT_NAME ON DEPARTMENTS FOR EACH ROW
BEGIN
    INSERT INTO DEPT_LOG (DEPARTMENT_ID, OLD_NAME, NEW_NAME, CHANGE_DATE)
    VALUES (:OLD.DEPARTMENT_ID, :OLD.DEPARTMENT_NAME, NEW.DEPARTMENT_NAME, SYSTIMESTAMP);
END;
/
---- Update department name
UPDATE DEPARTMENTS
SET DEPARTMENT_NAME = 'New IT Dept'
WHERE DEPARTMENT_ID = 60;

---- Check log
SELECT * FROM DEPT_LOG WHERE DEPARTMENT_ID = 60;



----Q4
--Creating a new Job History table for the fields are different as per Question requirement 
CREATE TABLE JOB HISTORY_NEW (
    EMPLOYEE_ID NUMBER,
    OLD_JOB_ID VARCHAR2 (10),
    NEW_JOB_ID VARCHAR2 (10),
    CHANGE DATE TIMESTAMP
);
CREATE OR REPLACE TRIGGER trg_job_change AFTER UPDATE OF JOB_ID ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF OLD.JOB_ID != NEW.JOB_ID THEN
        INSERT INTO JOB_HISTORY_NEW (EMPLOYEE_ID, OLD_JOB_ID, NEW_JOB_ID, CHANGE_DATE) 
        VALUES (:OLD. EMPLOYEE_ID, OLD. JOB ID, NEW.JOB_ID, SYSTIMESTAMP);
    END IF;
END;
/
--Change job
UPDATE EMPLOYEES
SET JOB_ID = 'SA_REP'
WHERE EMPLOYEE_ID = 202;

-- Check history
SELECT FROM JOB HISTORY NEW WHERE EMPLOYEE_ID = 202;



----Q5
CREATE OR REPLACE TRIGGER trg_dept_delete BEFORE DELETE ON DEPARTMENTS 
FOR EACH ROW
DECLARE
    V_count NUMBER;
BEGIN
END;
    SELECT COUNT(*) INTO v_count FROM EMPLOYEES WHERE DEPARTMENT_ID = : OLD. DEPARTMENT_ID; 
    IF v_count > 0 THEN
        RAISE APPLICATION_ERROR (-20002, 'Cannot delete department with employees.'); 
    END IF;
END;
/

--Should FAIL if employees exist
DELETE FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 60;



----Q6
---- Add TOTAL_SALARY Column if not exists
ALTER TABLE DEPARTMENTS ADD (TOTAL_SALARY NUMBER);

CREATE OR REPLACE TRIGGER trg_total_salary AFTER INSERT OR UPDATE OF SALARY ON EMPLOYEES 
BEGIN
    ---- Update total salary for all departments
    UPDATE DEPARTMENTS d
    SET TOTAL_SALARY = (SELECT SUM(SALARY) FROM EMPLOYEES e WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID);
END;
/
--Testing Total Salary when we update salary
UPDATE EMPLOYEES
SET Salary 7000
WHERE EMPLOYEE_ID = 202;


---- Insert employee
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE NUMBER, HIRE DATE, JOB_ID, SALARY, DEPARTMENT_ID)
VALUES (208, 'Test2', 'User2', 'testUser', '650.875.4887', SYSDATE, 'HR_REP', 14000, 60);
SELECT * FROM DEPARTMENTS;  ---- Check Total Salary



----Q7
CREATE TABLE EMPLOYEE_TERMINATION (
    EMPLOYEE_ID NUMBER,
    FIRST NAME VARCHAR2(50),
    LAST NAME VARCHAR2(50), 
    DEPARTMENT_ID NUMBER,
    TERMINATION_DATE TIMESTAMP
);
CREATE OR REPLACE TRIGGER trg employee_delete AFTER DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEE_TERMINATION (EMPLOYEE_ID, FIRST_NAME, LAST NAME, DEPARTMENT_ID, TERMINATION_DATE) 
    VALUES (:OLD. EMPLOYEE_ID, OLD. FIRST NAME, OLD. LAST_NAME, OLD. DEPARTMENT_ID, SYSTIMESTAMP);
END;
/
DELETE FROM JOB HISTORY 
WHERE EMPLOYEE_ID = 202; ---FOREIGN KEY ISSUE RAISED SO HAD TO DELTE HERE MANUALLY (ig no DELETE CASCADE WAS USED DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 202;
SELECT * FROM EMPLOYEE TERMINATION WHERE EMPLOYEE ID = 202;



----Q8
CREATE OR REPLACE TRIGGER trg_hire_date_check BEFORE INSERT ON EMPLOYEES 
FOR EACH ROW
BEGIN
    IF NEW.HIRE_DATE < DATE '1990-01-01' THEN
        RAISE_APPLICATION_ERROR(-20003, 'Hire date cannot be earlier than Jan 1, 1990.');
    END IF;
END;
/
----Should FAIL
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY) 
VALUES (997, 'old', 'Employee', 'oldemp', DATE '1985-01-01', 'IT_PROG', 3000);



----Q9
CREATE TABLE SALARY_HISTORY (
    EMPLOYEE_ID NUMBER,
    OLD_SALARY NUMBER,
    NEW SALARY NUMBER, 
    CHANGE_DATE TIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_salary_history AFTER UPDATE OF SALARY ON EMPLOYEES FOR EACH ROW
BEGIN
    INSERT INTO SALARY_HISTORY (EMPLOYEE_ID, OLD_SALARY, NEW_SALARY, CHANGE_DATE)
    VALUES (:OLD. EMPLOYEE_ID, OLD.SALARY, NEW.SALARY, SYSTIMESTAMP);
END;
/
-- Update salary
UPDATE EMPLOYEES
SET SALARY = 4500
WHERE EMPLOYEE_ID = 208;

----Check history
SELECT * FROM SALARY_HISTORY WHERE EMPLOYEE_ID = 208;



----Q10
-- Add column MANAGER_LEVEL to EMPLOYEES if not exists
ALTER TABLE EMPLOYEES ADD (MANAGER LEVEL NUMBER);

CREATE OR REPLACE TRIGGER trg_manager_level BEFORE INSERT ON EMPLOYEES 
FOR EACH ROW
BEGIN
    IF NEW.MANAGER_ID IS NOT NULL THEN
        DECLARE
            v_job VARCHAR2 (20);
        BEGIN
            ----Get manager's job
            SELECT JOB_ID INTO v_job FROM EMPLOYEES
            WHERE EMPLOYEE_ID = NEW.MANAGER_ID;
            ---- Assign MANAGER_LEVEL based on manager's job
            IF v_job = 'AD_PRES' THEN
                :NEW.MANAGER_LEVEL = 5;
            ELSIF v_job = 'AD_VP' THEN
                :NEW.MANAGER_LEVEL := 4;
            ELSIF v_job IN ('AD ASST', 'FI_MGR', 'AC_MGR', 'MK_MAN') THEN 
                :NEW.MANAGER_LEVEL := 3;
            ELSIF v job IN ('ST MAN', 'PU_MAN', 'SA_MAN') THEN
                :NEW.MANAGER_LEVEL = 2;
            ELSE
                :NEW.MANAGER_LEVEL := 1; all other employees
            END IF;
        END;
    ELSE
        :NEW.MANAGER_LEVEL := 0; ---- No manager assigned
    END IF;
END;
/


--- Insert a new employee under AD_VP (Neena Kochhar, EMPLOYEE_ID 101)
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY, MANAGER_ID, DEPARTMENT_ID) 
VALUES (202, 'Test', 'Employee', 'testemp', SYSDATE, 'IT_PROG', 5000, 101, 90);
---- Check result
SELECT EMPLOYEE_ID, FIRST_NAME, MANAGER_ID, MANAGER_LEVEL FROM EMPLOYEES
WHERE EMPLOYEE_ID = 202;



----Q11
CREATE OR REPLACE TRIGGER trg_check_dept_salary BEFORE INSERT OR UPDATE OF salary ON employees
FOR EACH ROW
DECLARE
    V_current_total NUMBER;
    v_projected NUMBER;
BEGIN
    -- Read from DEPARTMENTS table (as we have total salary colunm there from Q6)
    SELECT NVL (TOTAL_SALARY, 0) INTO V_current_total FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = NEW.DEPARTMENT_ID;

    -- On UPDATE subtract old salary, on INSERT old is 0
    v_projected := v_current_total - NVL(: OLD. SALARY, 0) + NEW.SALARY;
    IF v_projected > 200000 THEN
        RAISE APPLICATION_ERROR(-20001, 'Cannot apply salary change: department' || NEW.DEPARTMENT_ID || 'total would reach ' || v_projected || ', exceeding the limit.');
    END IF; 
END trg_check_dept_salary;

---- FAIL: dept 90 would exceed limit
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID)
VALUES (997, 'Test', 'HighSalary', 'highsal', SYSDATE, 'IT_PROG', 150000, 90);

----FAIL: update blocked properly
UPDATE EMPLOYEES SET SALARY = 49999 WHERE EMPLOYEE_ID = 208;    ----will increase
UPDATE EMPLOYEES SET SALARY = 49999 WHERE EMPLOYEE_ID = 107;    ----will increase
UPDATE EMPLOYEES SET SALARY = 49999 WHERE EMPLOYEE_ID = 106;    ----will increase
UPDATE EMPLOYEES SET SALARY = 49999 WHERE EMPLOYEE_ID = 105;    ----will throw error



----Q12
---- Step 1: Check salary BEFORE promotion
SELECT EMPLOYEE_ID, JOB_ID, SALARY FROM EMPLOYEES
WHERE EMPLOYEE_ID = 208;


-- Create JOB HIERARCHY table (doesn't exist, so we create it)
CREATE TABLE JOB HIERARCHY (
    JOB_ID VARCHAR2 (10) PRIMARY KEY,
    JOB_LEVEL NUMBER
);
----Populate with jobs that exist in EMPLOYEES table
INSERT INTO JOB HIERARCHY VALUES ('AD_VP', 5);
INSERT INTO JOB HIERARCHY VALUES ('AD_ASST', 4);
INSERT INTO JOB HIERARCHY VALUES ('AC_MGR', 3);
INSERT INTO JOB HIERARCHY VALUES ('FI_MGR', 3);
INSERT INTO JOB HIERARCHY VALUES ('PU_MAN', 2);
INSERT INTO JOB HIERARCHY VALUES ('ST_MAN', 2);
INSERT INTO JOB HIERARCHY VALUES ('SA_MAN', 2);
INSERT INTO JOB HIERARCHY VALUES ('MK_MAN', 2);
INSERT INTO JOB HIERARCHY VALUES ('IT_PROG', 1);
INSERT INTO JOB HIERARCHY VALUES ('FI_ACCOUNT', 4);
INSERT INTO JOB HIERARCHY VALUES ('AC_ACCOUNT', 4);
INSERT INTO JOB HIERARCHY VALUES ('SA_REP', 1);
INSERT INTO JOB HIERARCHY VALUES ('HR_REP', 1);
INSERT INTO JOB HIERARCHY VALUES ('PR_REP', 1);
INSERT INTO JOB HIERARCHY VALUES ('MK_REP', 1);
INSERT INTO JOB HIERARCHY VALUES ('PU_CLERK', 1);
INSERT INTO JOB HIERARCHY VALUES ('ST_CLERK', 1);
INSERT INTO JOB HIERARCHY VALUES ('SH_CLERK', 1);
COMMIT;


CREATE OR REPLACE TRIGGER trg_job_promotion_bonus BEFORE UPDATE OF JOB_ID ON EMPLOYEES 
FOR EACH ROW
DECLARE
    v_old_level NUMBER;
    v_new_level NUMBER;
BEGIN
    ---- Get job levels, default 0 if not found 
    SELECT NVL(JOB_LEVEL, 0) INTO v_old_level FROM JOB HIERARCHY 
    WHERE JOB_ID = OLD. JOB_ID;
    
    SELECT NVL (JOB_LEVEL, 0) INTO v_new_level FROM JOB HIERARCHY 
    WHERE JOB_ID = NEW.JOB_ID;

    -- if promoted to higher level, apply 5% bonus directly to :NEW.SALARY 
    IF v new level > v_old_level THEN
        :NEW.SALARY := NEW.SALARY* 1.05; 
        DBMS_OUTPUT.PUT_LINE('5% bonus applied to Employee' || NEW.EMPLOYEE_ID || ' for promotion from ' || :OLD.JOB_ID || ' to ' || :NEW.JOB_ID);
    END IF;
END;
/


---- Step 2: Now promote to FI_MGR (level 7 > level 3, bonus should apply) 
UPDATE EMPLOYEES 
SET JOB_ID = 'FI_MGR' 
WHERE EMPLOYEE_ID = 208;

----Step 3: Check salary AFTER promotion (should be 14000 1.05 = 14700) 
SELECT EMPLOYEE_ID, JOB_ID, SALARY FROM EMPLOYEES 
WHERE EMPLOYEE_ID = 208;



----Q13

---- Add a test department and employee
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (999, 'Temp Dept');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID)
VALUES (998, 'Archive', 'Test', 'archtest', SYSDATE, 'HR_REP', 3000, 999);

SELECT * FROM DEPARTMENTS WHERE Department_ID = 999;

CREATE TABLE EMPLOYEE_ARCHIVE (
    EMPLOYEE_ID NUMBER,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(20),
    PHONE_NUMBER NUMBER,
    HIRE_DATE DATE,
    JOB_ID VARCHAR2(10),
    SALARY NUMBER,
    DEPARTMENT_ID NUMBER,
    ARCHIVE_DATE TIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_archive_dept_employees BEFORE DELETE ON DEPARTMENTS
FOR EACH ROW
BEGIN
    --Step 1: Archive all employees of this department
    INSERT INTO EMPLOYEE_ARCHIVE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID, ARCHIVE_DATE)

    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID, SYSTIMESTAMP FROM EMPLOYEES
    WHERE DEPARTMENT_ID = OLD.DEPARTMENT_ID;

    ---- Step 2: Remove employees so FK constraint doesn't block dept deletion
    DELETE FROM EMPLOYEES WHERE DEPARTMENT_ID = : OLD.DEPARTMENT_ID;
    DBMS_OUTPUT.PUT_LINE('Archived and removed employees for Department' || :OLD.DEPARTMENT_ID);
END;
/


---- Note: Q5 trigger (trg_dept_delete) blocks deletion if employees exist.
---- To test Q13, disable Q5 trigger first, or test on a department with no employees
---- but employees are added manually for the sake of testing:
ALTER TRIGGER trg_dept_delete DISABLE;

---- Delete dept -> should archive employee 998 first 
DELETE FROM DEPARTMENTS WHERE DEPARTMENT_ID = 999;

----Verify archive
SELECT * FROM EMPLOYEE_ARCHIVE WHERE DEPARTMENT_ID = 999;
ALTER TRIGGER trg_dept_delete ENABLE;



----Q14
----Test: Change manager of employee 208 to someone in a different department
----Employee 208 has Manager =102 and dept = 90, Manager_ID = 103 (Alexander Hunlod) is in dept 60 
SELECT EMPLOYEE_ID, FIRST_NAME, MANAGER_ID, DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 208;

CREATE GLOBAL TEMPORARY TABLE TEMP_MANAGER_SYNC (
    EMP ID NUMBER,
    MGR_ID NUMBER,
    DEPT_ID NUMBER
) ON COMMIT PRESERVE ROWS;

CREATE OR REPLACE TRIGGER trg_sync_dept_row BEFORE UPDATE OF MANAGER_ID ON EMPLOYEES
FOR EACH ROW
BEGIN
    INSERT INTO TEMP MANAGER SYNC (EMP_ID, MGR_ID, DEPT_ID)
    VALUES (:NEW.EMPLOYEE_ID, :NEW.MANAGER_ID, :NEW.DEPARTMENT_ID);
END;
/

CREATE OR REPLACE TRIGGER trg_sync_dept_stmt AFTER UPDATE OF MANAGER_ID ON EMPLOYEES
DECLARE
BEGIN
    FOR rec IN (SELECT FROM TEMP_MANAGER_SYNC) LOOP
        UPDATE EMPLOYEES e
        SET DEPARTMENT ID = (
            SELECT DEPARTMENT_ID FROM EMPLOYEES
            WHERE EMPLOYEE_ID = rec.MGR_ID
        )WHERE e.EMPLOYEE_ID = rec.EMP_ID; 
    END LOOP;
END;
/


---- Test: Change manager of employee 208 to someone in a different department
---- Employee 208 has Manager =102 and dept = 90, Manager_ID = 103 (Alexander Hunlod) is in dept 60 
SELECT EMPLOYEE_ID, FIRST_NAME, MANAGER_ID, DEPARTMENT_ID FROM EMPLOYEES 
WHERE EMPLOYEE_ID = 208; 

UPDATE EMPLOYEES 
SET MANAGER_ID = 103 
WHERE EMPLOYEE_ID = 208;

-- Department should now match manager 103's department (60)
SELECT EMPLOYEE_ID, FIRST_NAME, MANAGER_ID, DEPARTMENT_ID FROM EMPLOYEES 
WHERE EMPLOYEE_ID = 208;



----Q15
CREATE OR REPLACE TRIGGER trg_unique_employee BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
    V_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM EMPLOYEES
    WHERE FIRST_NAME = NEW.FIRST_NAME AND LAST_NAME = NEW. LAST_NAME; 
    
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20005, 'Employee with same first and last name already exists.');
    END IF;
END;
/

---- Should FAIL if same name exists
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST NAME, LAST_NAME, EMAIL, HIRE DATE, JOB_ID, SALARY)
VALUES (209, 'Test2', 'User2', 'duplicate', SYSDATE, 'IT PROG', 3000);