---- Q1
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS Employee,
       m.FIRST_NAME || ' ' || m.LAST_NAME AS Manager
FROM EMPLOYEES e
LEFT JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID;

---- Q2
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS Employee,
       e.SALARY AS Employee_Salary,
       m.SALARY AS Manager_Salary
FROM EMPLOYEES e
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID
WHERE e.SALARY > m.SALARY;

---- Q3
SELECT d.DEPARTMENT_NAME FROM DEPARTMENTS d
LEFT JOIN EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
WHERE e.EMPLOYEE_ID IS NULL;

---- Q4
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS Employee,
       m.FIRST_NAME || ' ' || m.LAST_NAME AS Manager
FROM EMPLOYEES e
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID
WHERE e.HIRE_DATE < m.HIRE_DATE;

---- Q5
SELECT e1.FIRST_NAME || ' ' || e1.LAST_NAME AS Emp1,
       e2.FIRST_NAME || ' ' || e2.LAST_NAME AS Emp2,
       e1.DEPARTMENT_ID
FROM EMPLOYEES e1
JOIN EMPLOYEES e2 ON e1.DEPARTMENT_ID = e2.DEPARTMENT_ID AND e1.EMPLOYEE_ID < e2.EMPLOYEE_ID
WHERE e1.DEPARTMENT_ID IS NOT NULL;

---- Q6
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS Employee, l.CITY
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID;

---- Q7
SELECT FIRST_NAME || ' ' || LAST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID FROM EMPLOYEES
    WHERE FIRST_NAME = 'Steven' AND LAST_NAME = 'King'
)
AND NOT (FIRST_NAME = 'Steven' AND LAST_NAME = 'King');

---- Q8
SELECT FIRST_NAME || ' ' || LAST_NAME, SALARY FROM EMPLOYEES e
WHERE SALARY > (
    SELECT AVG(SALARY) FROM EMPLOYEES
    WHERE DEPARTMENT_ID = e.DEPARTMENT_ID
);

---- Q9
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME,
       COALESCE(d.DEPARTMENT_NAME, 'No Department')
FROM EMPLOYEES e
LEFT JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

---- Q10
SELECT FIRST_NAME || ' ' || LAST_NAME AS FullName FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN ( SELECT EMPLOYEE_ID FROM JOB_HISTORY );

---- Q11
SELECT JOB_ID FROM EMPLOYEES UNION
SELECT JOB_ID FROM JOB_HISTORY;

---- Q12
SELECT JOB_ID FROM EMPLOYEES MINUS
SELECT JOB_ID FROM JOB_HISTORY;

---- Q13
SELECT EMPLOYEE_ID FROM EMPLOYEES INTERSECT
SELECT EMPLOYEE_ID FROM JOB_HISTORY;

---- Q14
SELECT DEPARTMENT_ID FROM EMPLOYEES INTERSECT
SELECT DEPARTMENT_ID FROM JOB_HISTORY;

---- Q15
SELECT EMPLOYEE_ID FROM EMPLOYEES UNION
SELECT EMPLOYEE_ID FROM JOB_HISTORY;

---- Q16
SELECT EMPLOYEE_ID FROM JOB_HISTORY
MINUS
SELECT EMPLOYEE_ID FROM EMPLOYEES;

---- Q17
SELECT JOB_ID FROM EMPLOYEES UNION ALL
SELECT JOB_ID FROM JOB_HISTORY;

---- Q18
SELECT DEPARTMENT_ID FROM EMPLOYEES INTERSECT
SELECT DEPARTMENT_ID FROM JOB_HISTORY;

---- Q19
SELECT EMPLOYEE_ID FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (
    SELECT EMPLOYEE_ID FROM JOB_HISTORY
    WHERE JOB_ID <> (
        SELECT JOB_ID FROM EMPLOYEES e
        WHERE e.EMPLOYEE_ID = JOB_HISTORY.EMPLOYEE_ID
    )
);

---- Q20
SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME FROM EMPLOYEES e
WHERE EXISTS (
    SELECT 1 FROM JOB_HISTORY j
    WHERE j.EMPLOYEE_ID = e.EMPLOYEE_ID
    AND j.JOB_ID <> e.JOB_ID
);

---- Q21
CREATE VIEW emp_dept_salary AS
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS Name,
       d.DEPARTMENT_NAME, e.SALARY
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

---- Q22
CREATE VIEW high_salary_emp AS
SELECT * FROM EMPLOYEES
WHERE SALARY > 10000;

---- Q23
CREATE VIEW emp_manager AS
SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS Employee,
       m.FIRST_NAME || ' ' || m.LAST_NAME AS Manager
FROM EMPLOYEES e
LEFT JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID;

---- Q24
CREATE VIEW dept_avg_salary AS
SELECT DEPARTMENT_ID, AVG(SALARY) AS Avg_Salary FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

---- Q25
CREATE VIEW emp_full_details AS
SELECT e.*, d.DEPARTMENT_NAME, l.CITY
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID;

---- Q26
CREATE VIEW salary_check AS
SELECT * FROM EMPLOYEES
WHERE SALARY > 5000
WITH CHECK OPTION;

---- Q27
CREATE VIEW read_only_history AS
SELECT * FROM JOB_HISTORY
WITH READ ONLY;

---- Q28
CREATE VIEW all_jobs AS
SELECT JOB_ID FROM EMPLOYEES UNION
SELECT JOB_ID FROM JOB_HISTORY;

---- Q29
-- Update through view
UPDATE high_salary_emp
SET SALARY = SALARY + 1;

---- Q30
CREATE VIEW above_avg AS
SELECT * FROM EMPLOYEES e
WHERE SALARY > (
    SELECT AVG(SALARY) FROM EMPLOYEES
    WHERE DEPARTMENT_ID = e.DEPARTMENT_ID
);

---- Q31
CREATE VIEW emp_mgr_dept AS
SELECT e.FIRST_NAME emp, m.FIRST_NAME mgr, e.DEPARTMENT_ID e_dept, m.DEPARTMENT_ID m_dept
FROM EMPLOYEES e
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID;

SELECT * FROM emp_mgr_dept
WHERE e_dept <> m_dept;

---- Q32
CREATE VIEW emp_city AS
SELECT e.*, l.CITY FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID;

SELECT CITY FROM emp_city
GROUP BY CITY HAVING COUNT(*) > 5;

---- Q33
CREATE VIEW emp_dept_avg AS
SELECT e.*, AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID) avg_sal
FROM EMPLOYEES e;

SELECT * FROM emp_dept_avg
WHERE SALARY > avg_sal;

---- Q34
CREATE VIEW emp_history AS SELECT e.EMPLOYEE_ID, j.DEPARTMENT_ID
FROM EMPLOYEES e
JOIN JOB_HISTORY j ON e.EMPLOYEE_ID = j.EMPLOYEE_ID;

SELECT EMPLOYEE_ID FROM emp_history
GROUP BY EMPLOYEE_ID
HAVING COUNT(DISTINCT DEPARTMENT_ID) > 1;

---- Q35
CREATE VIEW dept_count AS
SELECT DEPARTMENT_ID, COUNT(*) cnt FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT * FROM dept_count
WHERE cnt > (SELECT AVG(cnt) FROM dept_count);

---- Q36
CREATE VIEW emp_mgr_salary AS
SELECT e.EMPLOYEE_ID, e.SALARY emp_sal, m.SALARY mgr_sal FROM EMPLOYEES e
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID;

SELECT * FROM emp_mgr_salary
WHERE emp_sal > mgr_sal;

---- Q37
CREATE VIEW emp_city_mgr AS
SELECT e.EMPLOYEE_ID, l.CITY, m.EMPLOYEE_ID mgr_id, l2.CITY mgr_city FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID
JOIN DEPARTMENTS d2 ON m.DEPARTMENT_ID = d2.DEPARTMENT_ID
JOIN LOCATIONS l2 ON d2.LOCATION_ID = l2.LOCATION_ID;

SELECT * FROM emp_city_mgr
WHERE CITY = mgr_city;

---- Q38
CREATE VIEW job_compare AS
SELECT e.EMPLOYEE_ID, e.JOB_ID curr_job, j.JOB_ID past_job FROM EMPLOYEES e
JOIN JOB_HISTORY j ON e.EMPLOYEE_ID = j.EMPLOYEE_ID;

SELECT * FROM job_compare
WHERE curr_job = past_job;

---- Q39
CREATE VIEW hire_compare AS
SELECT e.EMPLOYEE_ID, e.HIRE_DATE emp_hire, m.HIRE_DATE mgr_hire FROM EMPLOYEES e
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID;

SELECT * FROM hire_compare
WHERE emp_hire < mgr_hire;

---- Q40
CREATE VIEW emp_full AS
SELECT e.*, d.DEPARTMENT_NAME, j.JOB_TITLE FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN JOBS j ON e.JOB_ID = j.JOB_ID;

-- Try update
UPDATE emp_full SET SALARY = SALARY - 1000;
SELECT * FROM emp_full;