----Q1
SET SERVEROUTPUT ON;
DECLARE
    v_emp_id Employees.Employee_ID%TYPE := &Employee_ID;
    v_salary Employees.Salary%TYPE;
    v_dept_id Employees.Department_ID%TYPE;
    v_salary_cat VARCHAR2(30);
    v_dept_class VARCHAR2(30);
BEGIN
    SELECT Salary, Department_ID INTO v_salary, v_dept_id FROM EMPLOYEES
    WHERE Employee_ID = v_emp_id;

    v_salary_cat :=
        CASE
            WHEN v_salary < 5000 THEN 'LOW'
            WHEN v_salary BETWEEN 5000 AND 10000 THEN 'MEDIUM'
            ELSE 'HIGH'
        END;

    v_dept_class :=
        CASE
            WHEN v_dept_id IN (10, 20) THEN 'ADMIN/IT CORE'
            WHEN v_dept_id IN (30, 50) THEN 'SALES/OPS'
            ELSE 'OTHER'
        END;

    DBMS_OUTPUT.PUT_LINE('Employee ID: ' || v_emp_id);
    DBMS_OUTPUT.PUT_LINE('Salary Category: ' || v_salary_cat);
    DBMS_OUTPUT.PUT_LINE('Department Classification: ' || v_dept_class);
    DBMS_OUTPUT.PUT_LINE('Status: ' || v_salary_cat || ' - ' || v_dept_class);
END;
/


----Q2
SET SERVEROUTPUT ON;
DECLARE
    V_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_JOB_ID EMPLOYEES.JOB_ID%TYPE;
    V_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
    FOR REC IN (SELECT EMPLOYEE_ID, JOB_ID, SALARY FROM EMPLOYEES) LOOP

        V_EMP_ID := REC.EMPLOYEE_ID;
        V_JOB_ID := REC.JOB_ID;
        V_SALARY := REC.SALARY;

        IF V_JOB_ID LIKE '%IT%' AND V_SALARY > 8000 THEN
            DBMS_OUTPUT.PUT_LINE(V_EMP_ID || ' => TECHNICAL RECOGNITION');
        ELSE
            DBMS_OUTPUT.PUT_LINE(V_EMP_ID || ' => STANDARD CLASSIFICATION');
        END IF;

    END LOOP;
END;
/


----Q3
SET SERVEROUTPUT ON;
DECLARE
    V_SALARY_LEVEL VARCHAR2(20);
    V_PERF_LABEL VARCHAR2(30);
BEGIN
    FOR REC IN (SELECT EMPLOYEE_ID, JOB_ID, SALARY FROM EMPLOYEES) LOOP

        V_SALARY_LEVEL :=
            CASE
                WHEN REC.SALARY < 5000 THEN 'LOW'
                WHEN REC.SALARY BETWEEN 5000 AND 12000 THEN 'MID'
                ELSE 'HIGH'
            END;

        V_PERF_LABEL :=
            CASE
                WHEN REC.JOB_ID LIKE '%MAN%' THEN 'LEADER'
                WHEN REC.JOB_ID LIKE '%DEV%' THEN 'EXECUTOR'
                ELSE 'SUPPORT'
            END;

        DBMS_OUTPUT.PUT_LINE(REC.EMPLOYEE_ID || ' => ' || V_SALARY_LEVEL || ' | ' || V_PERF_LABEL);
    END LOOP;
END;
/


----Q4
SET SERVEROUTPUT ON;
DECLARE
    V_COMM NUMBER;
    V_STATUS VARCHAR2(30);
BEGIN
    FOR REC IN (SELECT EMPLOYEE_ID, SALARY, COMMISSION_PCT FROM EMPLOYEES) LOOP
        V_COMM := NVL(REC.COMMISSION_PCT, 0);

        IF REC.SALARY > 10000 AND V_COMM > 0.2 THEN
            V_STATUS := 'EXCELLENT';
        ELSIF REC.SALARY > 7000 THEN
            V_STATUS := 'GOOD';
        ELSE
            V_STATUS := 'AVERAGE';
        END IF;

        DBMS_OUTPUT.PUT_LINE(REC.EMPLOYEE_ID || ' => ' || V_STATUS);
    END LOOP;
END;
/


----Q5
SET SERVEROUTPUT ON;
DECLARE
    V_TOTAL NUMBER;
    V_AVG NUMBER;
    V_BUDGET VARCHAR2(20);
BEGIN
    FOR D IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS) LOOP
        SELECT NVL(SUM(SALARY),0), NVL(AVG(SALARY),0)
        INTO V_TOTAL, V_AVG
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID = D.DEPARTMENT_ID;

        V_BUDGET :=
            CASE
                WHEN V_TOTAL > 50000 THEN 'HIGH BUDGET'
                WHEN V_TOTAL BETWEEN 20000 AND 50000 THEN 'MEDIUM BUDGET'
                ELSE 'LOW BUDGET'
            END;
        DBMS_OUTPUT.PUT_LINE('DEPT ' || D.DEPARTMENT_ID || ' TOTAL: ' || V_TOTAL || ' AVG: ' || V_AVG || ' => ' || V_BUDGET);
    END LOOP;
END;
/


----Q6
SET SERVEROUTPUT ON;
DECLARE
    V_DEPT_ID EMPLOYEES.DEPARTMENT_ID%TYPE := &DEPT_ID;
    V_JOB_CLASS VARCHAR2(30);
    V_SALARY_STATUS VARCHAR2(30);
    V_PROMO_STATUS VARCHAR2(30);
BEGIN
    FOR REC IN (SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = V_DEPT_ID) LOOP
        V_JOB_CLASS :=
            CASE
                WHEN REC.JOB_ID LIKE '%MAN%' THEN 'MANAGER'
                WHEN REC.JOB_ID LIKE '%DEV%' THEN 'DEVELOPER'
                ELSE 'STAFF'
            END;

        V_SALARY_STATUS :=
            CASE
                WHEN REC.SALARY > 9000 THEN 'ELIGIBLE'
                ELSE 'NOT ELIGIBLE'
            END;

        V_PROMO_STATUS :=
            CASE
                WHEN REC.HIRE_DATE < ADD_MONTHS(SYSDATE, -60) THEN 'CONSIDER'
                ELSE 'WAIT'
            END;
        DBMS_OUTPUT.PUT_LINE(REC.EMPLOYEE_ID || ' | ' || V_JOB_CLASS || ' | ' || V_SALARY_STATUS || ' | ' || V_PROMO_STATUS);
    END LOOP;
END;
/


----Q7
SET SERVEROUTPUT ON;
DECLARE
    V_SALARY_GRADE VARCHAR2(20);
    V_JOB_CLASS VARCHAR2(20);
    V_EXP_CLASS VARCHAR2(20);
BEGIN
    FOR REC IN (SELECT EMPLOYEE_ID, JOB_ID, SALARY, HIRE_DATE FROM EMPLOYEES) LOOP
        V_SALARY_GRADE :=
            CASE
                WHEN REC.SALARY < 4000 THEN 'GRADE C'
                WHEN REC.SALARY < 9000 THEN 'GRADE B'
                ELSE 'GRADE A'
            END;

        V_JOB_CLASS :=
            CASE
                WHEN REC.JOB_ID LIKE '%IT%' THEN 'TECH'
                WHEN REC.JOB_ID LIKE '%SALES%' THEN 'BUSINESS'
                ELSE 'OTHER'
            END;

        V_EXP_CLASS :=
            CASE
                WHEN MONTHS_BETWEEN(SYSDATE, REC.HIRE_DATE) > 120 THEN 'EXPERT'
                WHEN MONTHS_BETWEEN(SYSDATE, REC.HIRE_DATE) > 60 THEN 'MID'
                ELSE 'JUNIOR'
            END;
        DBMS_OUTPUT.PUT_LINE(REC.EMPLOYEE_ID || ' => ' || V_SALARY_GRADE || ' | ' || V_JOB_CLASS || ' | ' || V_EXP_CLASS);
    END LOOP;
END;
/


----Q8
SET SERVEROUTPUT ON;
DECLARE
    V_SALARY_LEVEL VARCHAR2(20);
    V_COMM NUMBER;
    V_BONUS VARCHAR2(30);
BEGIN
    FOR REC IN (SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY, COMMISSION_PCT FROM EMPLOYEES) LOOP
        V_COMM := NVL(REC.COMMISSION_PCT, 0);
        V_SALARY_LEVEL :=
            CASE
                WHEN REC.SALARY < 5000 THEN 'LOW'
                WHEN REC.SALARY BETWEEN 5000 AND 10000 THEN 'MEDIUM'
                ELSE 'HIGH'
            END;

        IF REC.DEPARTMENT_ID IN (10, 20) AND V_SALARY_LEVEL = 'HIGH' AND V_COMM >= 0.2 THEN
            V_BONUS := 'ELITE BONUS';
        ELSIF REC.DEPARTMENT_ID IN (30, 50) AND V_SALARY_LEVEL IN ('MEDIUM','HIGH') AND V_COMM > 0 THEN
            V_BONUS := 'STANDARD BONUS';
        ELSIF V_COMM = 0 THEN
            V_BONUS := 'NO BONUS (NO COMMISSION)';
        ELSE
            V_BONUS := 'MINIMAL BONUS';
        END IF;
        DBMS_OUTPUT.PUT_LINE(REC.EMPLOYEE_ID || ' | DEPT ' || REC.DEPARTMENT_ID || ' | ' || V_SALARY_LEVEL || ' | COMM ' || V_COMM || ' => ' || V_BONUS);
    END LOOP;
END;
/


----Q9
SET SERVEROUTPUT ON;
DECLARE
    V_AVG NUMBER;
    V_JOB_CLASS VARCHAR2(30);
    V_PRIORITY VARCHAR2(30);
BEGIN
    SELECT AVG(SALARY) INTO V_AVG FROM EMPLOYEES;

    FOR REC IN (SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID, SALARY FROM EMPLOYEES) LOOP

        IF REC.SALARY < V_AVG THEN

            V_JOB_CLASS :=
                CASE
                    WHEN REC.JOB_ID LIKE '%MAN%' THEN 'MANAGER'
                    WHEN REC.JOB_ID LIKE '%DEV%' THEN 'DEVELOPER'
                    WHEN REC.JOB_ID LIKE '%SALES%' THEN 'SALES'
                    ELSE 'STAFF'
                END;

            V_PRIORITY :=
                CASE
                    WHEN REC.DEPARTMENT_ID IN (10, 20) THEN 'HIGH PRIORITY'
                    WHEN REC.DEPARTMENT_ID IN (30, 50) THEN 'MEDIUM PRIORITY'
                    ELSE 'LOW PRIORITY'
                END;
            DBMS_OUTPUT.PUT_LINE(REC.EMPLOYEE_ID || ' | ' || V_JOB_CLASS || ' | BELOW AVG | ' || V_PRIORITY);
        END IF;
    END LOOP;
END;
/


----Q10
SET SERVEROUTPUT ON;
DECLARE
    V_TIER VARCHAR2(20);
    V_JOB_CAT VARCHAR2(20);
    V_DEPT_CAT VARCHAR2(20);
BEGIN
    FOR REC IN (SELECT EMPLOYEE_ID, SALARY, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES ORDER BY SALARY DESC) LOOP
        V_TIER :=
            CASE
                WHEN REC.SALARY > 12000 THEN 'TIER 1'
                WHEN REC.SALARY > 7000 THEN 'TIER 2'
                ELSE 'TIER 3'
            END;

        V_JOB_CAT :=
            CASE
                WHEN REC.JOB_ID LIKE '%MAN%' THEN 'LEAD'
                WHEN REC.JOB_ID LIKE '%DEV%' THEN 'TECH'
                ELSE 'STAFF'
            END;

        V_DEPT_CAT :=
            CASE
                WHEN REC.DEPARTMENT_ID IN (10,20) THEN 'CORE'
                ELSE 'SUPPORT'
            END;
        DBMS_OUTPUT.PUT_LINE(REC.EMPLOYEE_ID || ' => ' || V_TIER || ' | ' || V_JOB_CAT || ' | ' || V_DEPT_CAT);
    END LOOP;
END;
/


----Q11
SET SERVEROUTPUT ON;
DECLARE
    V_SALARY_STATUS VARCHAR2(20);
    V_JOB_CLASS VARCHAR2(30);
BEGIN
    FOR D IN (SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS) LOOP
        DBMS_OUTPUT.PUT_LINE('DEPARTMENT: ' || D.DEPARTMENT_NAME);

        FOR E IN (SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = D.DEPARTMENT_ID) LOOP
            V_SALARY_STATUS :=
                CASE
                    WHEN E.SALARY < 5000 THEN 'LOW'
                    WHEN E.SALARY BETWEEN 5000 AND 10000 THEN 'MEDIUM'
                    ELSE 'HIGH'
                END;

            V_JOB_CLASS :=
                CASE
                    WHEN E.JOB_ID LIKE '%MAN%' THEN 'MANAGER'
                    WHEN E.JOB_ID LIKE '%DEV%' THEN 'DEVELOPER'
                    ELSE 'STAFF'
                END;
            DBMS_OUTPUT.PUT_LINE('  ' || E.FIRST_NAME || ' | ' ||  V_JOB_CLASS || ' | ' || V_SALARY_STATUS);
        END LOOP;
    END LOOP;
END;
/


----Q12
SET SERVEROUTPUT ON;
DECLARE
    V_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE := &EMP_ID;
    V_SALARY EMPLOYEES.SALARY%TYPE;
    V_JOB_ID EMPLOYEES.JOB_ID%TYPE;
    V_HIRE_DATE EMPLOYEES.HIRE_DATE%TYPE;
    V_STATUS VARCHAR2(50);
BEGIN
    SELECT SALARY, JOB_ID, HIRE_DATE INTO V_SALARY, V_JOB_ID, V_HIRE_DATE FROM EMPLOYEES
    WHERE EMPLOYEE_ID = V_EMP_ID;

    V_STATUS :=
        CASE
            WHEN V_SALARY < 5000 THEN 'GRADE C'
            WHEN V_SALARY BETWEEN 5000 AND 10000 THEN 'GRADE B'
            ELSE 'GRADE A'
        END;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID: ' || V_EMP_ID);
    DBMS_OUTPUT.PUT_LINE('SALARY GRADE: ' || V_STATUS);
    DBMS_OUTPUT.PUT_LINE('JOB CLASS: ' || V_JOB_ID);

    IF MONTHS_BETWEEN(SYSDATE, V_HIRE_DATE) > 60 THEN
        DBMS_OUTPUT.PUT_LINE('PROMOTION: ELIGIBLE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('PROMOTION: NOT ELIGIBLE');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('INVALID EMPLOYEE ID');
END;
/


----Q13
SET SERVEROUTPUT ON;
DECLARE
    V_NEW_SALARY NUMBER;
    V_CLASS VARCHAR2(30);
BEGIN
    FOR E IN (SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY, HIRE_DATE FROM EMPLOYEES) LOOP

        V_NEW_SALARY := E.SALARY;

        IF E.DEPARTMENT_ID IN (10, 20) THEN
            V_NEW_SALARY := V_NEW_SALARY * 1.10;
        ELSIF E.DEPARTMENT_ID IN (30, 50) THEN
            V_NEW_SALARY := V_NEW_SALARY * 1.05;
        END IF;

        IF MONTHS_BETWEEN(SYSDATE, E.HIRE_DATE) > 60 THEN
            V_NEW_SALARY := V_NEW_SALARY * 1.05;
        END IF;

        V_CLASS :=
            CASE
                WHEN V_NEW_SALARY < 5000 THEN 'LOW'
                WHEN V_NEW_SALARY BETWEEN 5000 AND 10000 THEN 'MEDIUM'
                ELSE 'HIGH'
            END;
        DBMS_OUTPUT.PUT_LINE(E.EMPLOYEE_ID || ' | OLD: ' || E.SALARY || ' | NEW: ' || V_NEW_SALARY || ' | CLASS: ' || V_CLASS);
    END LOOP;
END;
/


----Q14
SET SERVEROUTPUT ON;
DECLARE
    V_EXP_CLASS VARCHAR2(20);
    V_JOB_CLASS VARCHAR2(20);
    V_SAL_GRADE VARCHAR2(20);
BEGIN
    FOR E IN (SELECT EMPLOYEE_ID, JOB_ID, SALARY, HIRE_DATE FROM EMPLOYEES) LOOP
        V_EXP_CLASS :=
            CASE
                WHEN MONTHS_BETWEEN(SYSDATE, E.HIRE_DATE) < 36 THEN 'JUNIOR'
                WHEN MONTHS_BETWEEN(SYSDATE, E.HIRE_DATE) BETWEEN 36 AND 96 THEN 'MID'
                ELSE 'SENIOR'
            END;

        V_JOB_CLASS :=
            CASE
                WHEN E.JOB_ID LIKE '%MAN%' THEN 'MANAGEMENT'
                WHEN E.JOB_ID LIKE '%DEV%' THEN 'TECH'
                ELSE 'OTHER'
            END;

        V_SAL_GRADE :=
            CASE
                WHEN E.SALARY < 5000 THEN 'C'
                WHEN E.SALARY BETWEEN 5000 AND 10000 THEN 'B'
                ELSE 'A'
            END;
        DBMS_OUTPUT.PUT_LINE(E.EMPLOYEE_ID || ' => ' || V_EXP_CLASS || ' | ' || V_JOB_CLASS || ' | ' || V_SAL_GRADE);
    END LOOP;
END;
/


----Q15
SET SERVEROUTPUT ON;
DECLARE
    V_SAL_GRADE VARCHAR2(20);
    V_JOB_CLASS VARCHAR2(20);
    V_BONUS VARCHAR2(20);
BEGIN
    FOR E IN (SELECT EMPLOYEE_ID, JOB_ID, SALARY, DEPARTMENT_ID FROM EMPLOYEES) LOOP
        V_SAL_GRADE :=
            CASE
                WHEN E.SALARY < 5000 THEN 'LOW'
                WHEN E.SALARY BETWEEN 5000 AND 10000 THEN 'MID'
                ELSE 'HIGH'
            END;

        V_JOB_CLASS :=
            CASE
                WHEN E.JOB_ID LIKE '%MAN%' THEN 'MANAGER'
                WHEN E.JOB_ID LIKE '%DEV%' THEN 'DEVELOPER'
                ELSE 'STAFF'
            END;

        V_BONUS :=
            CASE
                WHEN E.SALARY > 10000 THEN 'ELIGIBLE'
                ELSE 'NOT ELIGIBLE'
            END;
        DBMS_OUTPUT.PUT_LINE(E.EMPLOYEE_ID || ' | ' || V_SAL_GRADE || ' | ' || V_JOB_CLASS || ' | ' || 'DEPT: ' || E.DEPARTMENT_ID || ' | ' ||  V_BONUS);
    END LOOP;
END;
/


----Q16
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE GET_EMP_DETAILS (P_EMP_ID NUMBER) AS
BEGIN
    FOR E IN (SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = P_EMP_ID) LOOP
        DBMS_OUTPUT.PUT_LINE(E.FIRST_NAME || ' | ' ||
                             E.JOB_ID || ' | ' ||
                             E.SALARY || ' | ' ||
                             E.DEPARTMENT_ID || ' | ' ||
                             E.HIRE_DATE);
    END LOOP;
END;
/

---- Running Q16 procedure
BEGIN
    GET_EMP_DETAILS(103);
END;
/


----Q17
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE RAISE_SALARY ( P_EMP_ID NUMBER, P_PERCENT NUMBER) AS
    V_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_SAL  EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT FIRST_NAME, SALARY INTO V_NAME, V_SAL FROM EMPLOYEES
    WHERE EMPLOYEE_ID = P_EMP_ID;

    V_SAL := V_SAL + (V_SAL * P_PERCENT / 100);

    UPDATE EMPLOYEES
    SET SALARY = V_SAL
    WHERE EMPLOYEE_ID = P_EMP_ID;

    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME: ' || V_NAME);
    DBMS_OUTPUT.PUT_LINE('UPDATED SALARY: ' || V_SAL);
EXCEPTION
    WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('EMPLOYEE NOT FOUND');
END;
/

----Running Q17 Procedure
BEGIN
    RAISE_SALARY(103, 10);
END;
/


----Q18
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE SHOW_DEPT_EMPLOYEES (P_DEPT_ID NUMBER) AS
BEGIN
    FOR REC IN (SELECT EMPLOYEE_ID, JOB_ID, SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = P_DEPT_ID) LOOP
        DBMS_OUTPUT.PUT_LINE(REC.EMPLOYEE_ID || ' | ' || REC.JOB_ID || ' | ' || REC.SALARY);
    END LOOP;
END;
/

----Running Q18 Procedure
BEGIN
    SHOW_DEPT_EMPLOYEES(50);
END;
/


----Q19
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE DEPT_SALARY_STATS (P_DEPT_ID NUMBER) AS
    V_COUNT NUMBER;
    V_TOTAL NUMBER;
    V_AVG NUMBER;
BEGIN
    SELECT COUNT(*), NVL(SUM(SALARY),0), NVL(AVG(SALARY),0) INTO V_COUNT, V_TOTAL, V_AVG FROM EMPLOYEES
    WHERE DEPARTMENT_ID = P_DEPT_ID;

    DBMS_OUTPUT.PUT_LINE('TOTAL EMPLOYEES: ' || V_COUNT);
    DBMS_OUTPUT.PUT_LINE('TOTAL SALARY: ' || V_TOTAL);
    DBMS_OUTPUT.PUT_LINE('AVERAGE SALARY: ' || V_AVG);
END;
/

----Running Q19 Procedure
BEGIN
    DEPT_SALARY_STATS(50);
END;
/


----Q20
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE JOB_EMP_REPORT (P_JOB_ID VARCHAR2) AS
BEGIN
    FOR REC IN (SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME, E.SALARY, E.HIRE_DATE FROM EMPLOYEES E
                JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                WHERE E.JOB_ID = P_JOB_ID) LOOP

        DBMS_OUTPUT.PUT_LINE(REC.EMPLOYEE_ID || ' | ' || REC.FIRST_NAME || ' | ' ||
                             REC.DEPARTMENT_NAME || ' | ' || REC.SALARY || ' | ' || REC.HIRE_DATE);
    END LOOP;
END;
/

----Running Q20 Procedure
BEGIN
    JOB_EMP_REPORT('IT_PROG');
END;
/
